name: Deploy to EC2

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.EC2_HOST }}  # Set this in your GitHub secrets
          USERNAME: ec2-user  # Default AWS EC2 username, adjust if necessary
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Set this in your GitHub secrets
        with:
          source: "target/*.jar"  # Adjust this path to where your JAR file is built
          target: "/home/ec2-user/"  # Adjust target directory as necessary

      - name: Restart Spring Boot app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl restart my-spring-boot-app.service  # Adjust this to your specific start/restart command
